Repository hql287/Manta, pull requests merged in 2018-03, with the labels that each got.

#231 quit app on linux/windows if the main window is closed
  app.js
Labels: enhancement

#237 Reimplemented invoice update action
  app/actions/__tests__/invoices.spec.js
  app/actions/invoices.jsx
  app/helpers/__mocks__/pouchDB.js
  app/helpers/__tests__/form.spec.js
  app/helpers/form.js
  app/helpers/pouchDB.js
  app/middlewares/FormMW.jsx
  app/middlewares/InvoicesMW.jsx
  app/middlewares/__tests__/InvoicesMW.spec.js
Labels: bug

#229 Add new languages
  app/components/settings/General.jsx
  i18n/de/common.json
  i18n/de/contacts.json
  i18n/de/dialog.json
  i18n/de/form.json
  i18n/de/index.js
  i18n/de/invoices.json
  i18n/de/messages.json
  i18n/de/preview.json
  i18n/de/settings.json
  i18n/de/tour.json
  i18n/fr/common.json
  i18n/fr/contacts.json
  i18n/fr/dialog.json
  i18n/fr/form.json
  i18n/fr/index.js
  i18n/fr/invoices.json
  i18n/fr/messages.json
  i18n/fr/preview.json
  i18n/fr/settings.json
  i18n/fr/tour.json
  i18n/i18n.js
  i18n/id/common.json
  i18n/id/contacts.json
  i18n/id/dialog.json
  i18n/id/form.json
  i18n/id/index.js
  i18n/id/invoices.json
  i18n/id/messages.json
  i18n/id/preview.json
  i18n/id/settings.json
  i18n/id/tour.json
  i18n/ko/common.json
  i18n/ko/contacts.json
  i18n/ko/dialog.json
  i18n/ko/form.json
  i18n/ko/invoices.json
  i18n/ko/messages.json
  i18n/ko/preview.json
  i18n/ko/settings.json
  i18n/ko/tour.json
  i18n/vi/form.json
  i18n/vi/settings.json
  i18n/zh-CN/form.json
  preview/components/sidebar/Language.jsx
Labels: feature-request, help-wanted

#238 add devtron condition to devtools extension loader
  app.js
Labels: enhancement

#240 add linux launcher category to electron-builder config
  electron-builder.yml
Labels: enhancement

#247 German date formats
  app/components/settings/_partials/invoice/Other.jsx
  i18n/i18n.js
Labels: enhancement

#245 Reflect changes on invoice immediately when profile's changed.
  app/actions/__tests__/invoices.spec.js
  app/middlewares/SettingsMW.jsx
  app/middlewares/__tests__/SettingsMW.spec.js
  main/preview-window.js
  preview/Viewer.jsx
  preview/actions/__test__/index.spec.js
  preview/actions/index.jsx
  preview/constants/actions.jsx
  preview/reducers/__test__/index.spec.js
  preview/reducers/index.jsx
Labels: bug

#226 Add GitHub Guidelines
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: doc

#255 Output taxID to templates if necessary
  preview/templates/business/components/Header.jsx
  preview/templates/minimal/components/Footer.jsx
  preview/templates/minimal/components/Header.jsx
Labels: bug

#235 Added Commandline Options
  README.md
  app.js
Labels: enhancement

#251 Fixed notification overlay bug
  app/components/settings/_partials/invoice/Other.jsx
Labels: bug

#258 Updated Screenshots section of ReadMe
  README.md
Labels: doc

#260 Fixed quantity display issue
  preview/templates/business/components/Main.jsx
  preview/templates/minimal/components/Main.jsx
Labels: bug

#262 Simplify auto check for updates
  app.js
  app/components/settings/General.jsx
  main/auto-check-updates.js
  main/updater.js
Labels: enhancement

#264 Migrated to webpack 4
  app.js
  app/index.html
  modal/index.html
  package.json
  preview/index.html
  tour/index.html
  webpack.config.js
  webpack.parts.js
  yarn.lock
Labels: enhancement, refactoring

#267 Allow changing logo size in templates
  app/components/settings/_partials/profile/Logo.jsx
  app/helpers/image.js
  i18n/en/preview.json
  preview/components/sidebar/LogoSize.jsx
  preview/containers/SideBar.jsx
  preview/reducers/index.jsx
  preview/templates/business/components/Logo.jsx
  preview/templates/minimal/components/Header.jsx
Labels: enhancement, feature-request, refactoring

#268 Make title bar visible on macOS
  app.js
  app/components/layout/AppNav.jsx
Labels: enhancement

#270 Refactor Accent Colour Component
  app/helpers/pouchDB.js
  preview/components/shared/index.js
  preview/components/sidebar/AccentColor.jsx
  preview/components/sidebar/Toggler.jsx
  preview/containers/MainContent.jsx
  preview/containers/SideBar.jsx
  preview/reducers/index.jsx
  preview/templates/business/components/Footer.jsx
  preview/templates/business/components/Header.jsx
  preview/templates/business/components/Main.jsx
  preview/templates/minimal/components/Header.jsx
Labels: refactoring

#272 Allow user to duplicate an invoice.
  app/actions/__tests__/invoices.spec.js
  app/actions/invoices.jsx
  app/components/invoices/Invoice.jsx
  app/components/invoices/__tests__/Invoice.spec.js
  app/components/invoices/__tests__/__snapshots__/Invoice.spec.js.snap
  app/constants/actions.jsx
  app/containers/Invoices.jsx
  app/middlewares/InvoicesMW.jsx
  app/middlewares/__tests__/InvoicesMW.spec.js
Labels: feature, feature-request

#257 Sidebar overflow fixes
  preview/components/shared/index.js
  preview/components/sidebar/Actions.jsx
  preview/containers/SideBar.jsx
  static/css/general.css
Labels: bug

#275 Added filtering invoices feature
  app/components/form/__tests__/__snapshots__/ItemsList.spec.jsx.snap
  app/components/invoices/__tests__/__snapshots__/Invoice.spec.js.snap
  app/components/shared/Button.jsx
  app/components/shared/Layout.jsx
  app/containers/Invoices.jsx
  app/containers/__tests__/Invoices.spec.js
  app/containers/__tests__/__snapshots__/Invoices.spec.js.snap
Labels: feature

#253 Added more languages
  app/components/settings/General.jsx
  i18n/de/settings.json
  i18n/en/settings.json
  i18n/i18n.js
  i18n/id/preview.json
  i18n/id/settings.json
  i18n/it/common.json
  i18n/it/contacts.json
  i18n/it/dialog.json
  i18n/it/form.json
  i18n/it/index.js
  i18n/it/invoices.json
  i18n/it/messages.json
  i18n/it/preview.json
  i18n/it/settings.json
  i18n/it/tour.json
  i18n/sk/common.json
  i18n/sk/contacts.json
  i18n/sk/dialog.json
  i18n/sk/form.json
  i18n/sk/index.js
  i18n/sk/invoices.json
  i18n/sk/messages.json
  i18n/sk/preview.json
  i18n/sk/settings.json
  i18n/sk/tour.json
  i18n/ur-PK/common.json
  i18n/ur-PK/contacts.json
  i18n/ur-PK/dialog.json
  i18n/ur-PK/form.json
  i18n/ur-PK/index.js
  i18n/ur-PK/invoices.json
  i18n/ur-PK/messages.json
  i18n/ur-PK/preview.json
  i18n/ur-PK/settings.json
  i18n/ur-PK/tour.json
  i18n/vi/settings.json
  i18n/zh-CN/settings.json
  preview/components/sidebar/Language.jsx
Labels: feature, help-wanted

#278 Added support for Windows 32 bit
  electron-builder.yml
Labels: enhancement, feature-request
